2020-06-07 23:03:34,449 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 86, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 9, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Flask\microblog\app\models.py", line 74, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
NameError: name 'app' is not defined
2020-06-07 23:04:37,394 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 86, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 9, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Flask\microblog\app\models.py", line 74, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
NameError: name 'app' is not defined
2020-06-07 23:04:49,655 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 86, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 9, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Flask\microblog\app\models.py", line 74, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
NameError: name 'app' is not defined
2020-06-07 23:07:45,621 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-07 23:07:50,420 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 86, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 14, in send_password_reset_email
    user=user, token=token),
  File "c:\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\python\python37\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\python\python37\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\python\python37\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\Flask\microblog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\python\python37\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\python\python37\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-06-07 23:13:33,375 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-07 23:36:56,288 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-07 23:38:52,791 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 86, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 9, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Flask\microblog\app\models.py", line 75, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'app' is not defined
2020-06-07 23:45:16,418 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
